version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops_app
    ports:
      - "8000:8000"  # для FastAPI
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      - minio

  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    ports:
      - "9000:9000"  # для S3
      - "9001:9001"  # MinIO
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

volumes:
  minio_data:
