# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: main.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'main.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\"\xa0\x01\n\rtrain_request\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12\x34\n\x0bhyperparams\x18\x02 \x03(\x0b\x32\x1f.train_request.HyperparamsEntry\x12\x11\n\tdata_path\x18\x03 \x01(\t\x1a\x32\n\x10HyperparamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\"\n\x0etrain_response\x12\x10\n\x08model_id\x18\x01 \x01(\t\"6\n\x0fpredict_request\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x11\n\tdata_path\x18\x02 \x01(\t\"3\n\x10predict_response\x12\x12\n\nprediction\x18\x01 \x03(\x02\x12\x0b\n\x03MSE\x18\x02 \x03(\x02\"\"\n\x0e\x64\x65lete_request\x12\x10\n\x08model_id\x18\x01 \x01(\t\"!\n\x0f\x64\x65lete_response\x12\x0e\n\x06status\x18\x01 \x01(\t\"1\n\x0fstatus_response\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06models\x18\x02 \x03(\t\"!\n\nmodel_list\x12\x13\n\x0bmodel_types\x18\x01 \x03(\t\"\x07\n\x05\x65mpty2\xf5\x01\n\x0cModelService\x12.\n\x0btrain_model\x12\x0e.train_request\x1a\x0f.train_response\x12&\n\x0fget_model_types\x12\x06.empty\x1a\x0b.model_list\x12.\n\x07predict\x12\x10.predict_request\x1a\x11.predict_response\x12\x31\n\x0c\x64\x65lete_model\x12\x0f.delete_request\x1a\x10.delete_response\x12*\n\x0eservice_status\x12\x06.empty\x1a\x10.status_responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAIN_REQUEST_HYPERPARAMSENTRY']._loaded_options = None
  _globals['_TRAIN_REQUEST_HYPERPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_TRAIN_REQUEST']._serialized_start=15
  _globals['_TRAIN_REQUEST']._serialized_end=175
  _globals['_TRAIN_REQUEST_HYPERPARAMSENTRY']._serialized_start=125
  _globals['_TRAIN_REQUEST_HYPERPARAMSENTRY']._serialized_end=175
  _globals['_TRAIN_RESPONSE']._serialized_start=177
  _globals['_TRAIN_RESPONSE']._serialized_end=211
  _globals['_PREDICT_REQUEST']._serialized_start=213
  _globals['_PREDICT_REQUEST']._serialized_end=267
  _globals['_PREDICT_RESPONSE']._serialized_start=269
  _globals['_PREDICT_RESPONSE']._serialized_end=320
  _globals['_DELETE_REQUEST']._serialized_start=322
  _globals['_DELETE_REQUEST']._serialized_end=356
  _globals['_DELETE_RESPONSE']._serialized_start=358
  _globals['_DELETE_RESPONSE']._serialized_end=391
  _globals['_STATUS_RESPONSE']._serialized_start=393
  _globals['_STATUS_RESPONSE']._serialized_end=442
  _globals['_MODEL_LIST']._serialized_start=444
  _globals['_MODEL_LIST']._serialized_end=477
  _globals['_EMPTY']._serialized_start=479
  _globals['_EMPTY']._serialized_end=486
  _globals['_MODELSERVICE']._serialized_start=489
  _globals['_MODELSERVICE']._serialized_end=734
# @@protoc_insertion_point(module_scope)
